In [3]:
import pandas as pd

In [4]:
c = pd.read_csv("customer_sales_messy.csv")

In [5]:
c.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [6]:
c.isnull().sum().sum()

np.int64(10)

In [7]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         53 non-null     int64
 1   Customer_Name    52 non-null     object
 2   City             51 non-null     object
 3   Product          53 non-null     object
 4   Category         52 non-null     object
 5   Quantity         53 non-null     int64
 6   Price            51 non-null     float64
 7   Order_Date       52 non-null     object
 8   Payment_Mode     52 non-null     object
 9   Salesperson      53 non-null     object
 10  Customer_Rating  51 non-null     float64
dtypes: float64(2), int64(2), object(7)
memory usage: 4.7+ KB

In [8]:
c.shape

(53, 11)

In [9]:
c.describe()

          Order_ID   Quantity         Price  Customer_Rating
count    53.000000  53.000000     51.000000        51.000000
mean   1024.584906   1.471698  10737.254902         4.196078
std      14.692272   0.696247  16851.970221         0.693386
min    1001.000000   1.000000    780.000000         3.000000
25%    1012.000000   1.000000   1975.000000         4.000000
50%    1024.000000   1.000000   3250.000000         4.000000
75%    1037.000000   2.000000   8350.000000         5.000000
max    1050.000000   4.000000  57000.000000         5.000000

In [10]:
c.duplicated().sum()

np.int64(2)

In [11]:
c.drop_duplicates()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [12]:
c.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Product', 'Category', 'Quantity',
       'Price', 'Order_Date', 'Payment_Mode', 'Salesperson',
       'Customer_Rating'],
      dtype='object')

In [13]:
c[c.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
5,1006,NaN,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [14]:
m = c.isnull().sum()

In [15]:
m_percentage = (c.isnull().mean()*100)

In [16]:
m_percentage

Order_ID           0.000000
Customer_Name      1.886792
City               3.773585
Product            0.000000
Category           1.886792
Quantity           0.000000
Price              3.773585
Order_Date         1.886792
Payment_Mode       1.886792
Salesperson        0.000000
Customer_Rating    3.773585
dtype: float64

In [17]:
c["Customer_Name"] = c["Customer_Name"].fillna("Unknown")

In [18]:
c.isnull().sum()

Order_ID           0
Customer_Name      0
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [19]:
c[c.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,NaN,2026-09-06,upi,Ravi,3.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,NaN,22/09/2026,UPI,Ravi,4.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [20]:
c["Price"] =c["Price"].fillna(c["Price"].min())

In [21]:
c

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [22]:
c[c.isnull().any(axis=1)]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
11,1012,Neha Singh,NaN,Office Chair,Furniture,1,6200.0,2026-09-08,UPI,Ravi,4.0
16,1017,Lakshmi Devi,Delhi,Headphones,Electronics,1,2900.0,2026/09/11,card,Suresh,NaN
21,1022,Rakesh Jain,Bangalore,Desk,Furniture,2,8200.0,13-09-2026,NaN,Ravi,4.0
28,1029,Anu Joseph,Kochi,Monitor,Electronics,1,11900.0,NaN,UPI,Suresh,5.0
34,1035,Geetha S,Pune,Headphones,NaN,1,3000.0,2026-09-20,Card,Suresh,5.0
45,1046,Kiran B,Pune,Desk,Furniture,1,8100.0,25-09-2026,Cash,Ravi,NaN
47,1048,Asha Nair,NaN,Laptop Stand,Accessories,1,2150.0,26-09-2026,UPI,Meena,5.0

In [23]:
c= c.dropna()

In [24]:
c[c.isnull().any(axis=1)]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Price, Order_Date, Payment_Mode, Salesperson, Customer_Rating]
Index: []

In [25]:
c

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,cash,Ravi,4.0
1,1002,Priya Sharma,chennai,Mouse,Electronics,2,850.0,01/09/2026,UPI,Meena,5.0
2,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,CARD,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,04/09/2026,Cash,Ravi,4.0
6,1007,Vijay Kumar,HYDERABAD,Laptop Stand,Accessories,2,2200.0,2026-09-05,cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,05-09-2026,UPI,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0
10,1011,Rohit Das,pune,Monitor,Electronics,1,11800.0,07/09/2026,cash,Meena,5.0
12,1013,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,09-09-2026,Card,Suresh,5.0
14,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,10/09/2026,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,11-09-2026,UPI,Meena,5.0
18,1019,Meena Krishnan,Hyderabad,Laptop,Electronics,1,56000.0,2026-09-12,Cash,Ravi,4.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,12/09/2026,Card,Suresh,3.0
20,1021,Nithya S,Chennai,Office Chair,Furniture,1,6400.0,2026-09-13,UPI,Meena,5.0
22,1023,Keerthi M,Bengaluru,Keyboard,Electronics,1,1900.0,2026-09-14,UPI,Suresh,4.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,14/09/2026,cash,Meena,5.0
24,1025,Pavithra R,Pune,Webcam,Accessories,1,3300.0,2026-09-15,Card,Ravi,4.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,15-09-2026,UPI,Suresh,3.0
26,1027,Ishita Sen,Kolkata,Laptop Stand,Accessories,2,2300.0,2026-09-16,Cash,Meena,5.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,16/09/2026,card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,17-09-2026,Cash,Meena,4.0
30,1031,Sowmya R,chennai,Office Chair,Furniture,2,6300.0,2026-09-18,UPI,Ravi,5.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,18/09/2026,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,2026/09/19,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,19-09-2026,UPI,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,20/09/2026,Cash,Meena,4.0
36,1037,Riya Kapoor,Kolkata,Monitor,Electronics,1,12100.0,2026-09-21,UPI,Ravi,5.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,21-09-2026,card,Suresh,4.0
38,1039,Farah Khan,Kochi,Desk,Furniture,1,7900.0,2026-09-22,Cash,Meena,5.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,22/09/2026,UPI,Ravi,4.0
40,1041,Divya Raj,Bangalore,Keyboard,Electronics,1,1800.0,2026-09-23,Card,Suresh,3.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,23-09-2026,cash,Meena,4.0
42,1043,Anita Roy,Delhi,Webcam,Accessories,2,3250.0,2026-09-24,UPI,Ravi,5.0
43,1044,Rahul Verma,CHENNAI,Laptop,Electronics,1,55500.0,24/09/2026,CARD,Suresh,4.0
44,1045,Priya Sharma,Chennai,Monitor,Electronics,1,12300.0,2026-09-25,upi,Meena,5.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,2026/09/26,Card,Suresh,3.0
48,1049,Maya S,Kochi,Mouse,Electronics,2,780.0,2026-09-27,Cash,Ravi,4.0
49,1050,Vikram J,Bengaluru,Office Chair,Furniture,1,6600.0,27/09/2026,Card,Suresh,5.0
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [26]:
p = pd.read_csv("customer_sales_messy.csv")

In [27]:
p.isnull().sum()

Order_ID           0
Customer_Name      1
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [28]:
p_new = p.dropna(subset=["Customer_Name"])

In [29]:
p_new.isnull().sum()

Order_ID           0
Customer_Name      0
City               2
Product            0
Category           1
Quantity           0
Price              2
Order_Date         1
Payment_Mode       1
Salesperson        0
Customer_Rating    2
dtype: int64

In [30]:
c[c.duplicated()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0

In [31]:
c[c["Order_ID"].duplicated()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
50,1003,RAHUL VERMA,CHENNAI,Keyboard,Electronics,1,1800.0,2026/09/02,upi,Ravi,4.0
51,1015,Ramesh B,KOCHI,Mouse,Electronics,3,800.0,2026-09-10,UPI,Meena,4.0
52,1010,Rohit Das,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [32]:
p_new["City"].str.upper()

0       CHENNAI
1       CHENNAI
2       CHENNAI
3     BANGALORE
4     BENGALURU
6     HYDERABAD
7        MUMBAI
8        MUMBAI
9          PUNE
10         PUNE
11          NaN
12      CHENNAI
13        KOCHI
14        KOCHI
15      CHENNAI
16        DELHI
17        DELHI
18    HYDERABAD
19       MUMBAI
20      CHENNAI
21    BANGALORE
22    BENGALURU
23    HYDERABAD
24         PUNE
25        DELHI
26      KOLKATA
27      KOLKATA
28        KOCHI
29      CHENNAI
30      CHENNAI
31    HYDERABAD
32       MUMBAI
33       MUMBAI
34         PUNE
35        DELHI
36      KOLKATA
37      KOLKATA
38        KOCHI
39      CHENNAI
40    BANGALORE
41    HYDERABAD
42        DELHI
43      CHENNAI
44      CHENNAI
45         PUNE
46         PUNE
47          NaN
48        KOCHI
49    BENGALURU
50      CHENNAI
51        KOCHI
52         PUNE
Name: City, dtype: object

In [33]:
p_new=p_new["City"].str.upper()

In [36]:
p_new["City"]=c["City"].str.strip()

In [37]:
p_new

0                                                 CHENNAI
1                                                 CHENNAI
2                                                 CHENNAI
3                                               BANGALORE
4                                               BENGALURU
6                                               HYDERABAD
7                                                  MUMBAI
8                                                  MUMBAI
9                                                    PUNE
10                                                   PUNE
11                                                    NaN
12                                                CHENNAI
13                                                  KOCHI
14                                                  KOCHI
15                                                CHENNAI
16                                                  DELHI
17                                                  DELHI
18                                              HYDERABAD
19                                                 MUMBAI
20                                                CHENNAI
21                                              BANGALORE
22                                              BENGALURU
23                                              HYDERABAD
24                                                   PUNE
25                                                  DELHI
26                                                KOLKATA
27                                                KOLKATA
28                                                  KOCHI
29                                                CHENNAI
30                                                CHENNAI
31                                              HYDERABAD
32                                                 MUMBAI
33                                                 MUMBAI
34                                                   PUNE
35                                                  DELHI
36                                                KOLKATA
37                                                KOLKATA
38                                                  KOCHI
39                                                CHENNAI
40                                              BANGALORE
41                                              HYDERABAD
42                                                  DELHI
43                                                CHENNAI
44                                                CHENNAI
45                                                   PUNE
46                                                   PUNE
47                                                    NaN
48                                                  KOCHI
49                                              BENGALURU
50                                                CHENNAI
51                                                  KOCHI
52                                                   PUNE
City    0       Chennai
1       chennai
2       CHENNA...
Name: City, dtype: object

In [38]:
p_new["City"]=c["City"].str.title()

In [40]:
c["Payment_Mode"]=c["Payment_Mode"].str.strip()

/tmp/ipykernel_3627/695477588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["Payment_Mode"]=c["Payment_Mode"].str.strip()

In [42]:
c["Payment_Mode"]=c["Payment_Mode"].str.title()

/tmp/ipykernel_3627/2693333775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["Payment_Mode"]=c["Payment_Mode"].str.title()

In [48]:
c["Customer_Name"] = (c["Customer_Name"].str.strip().str.title())
c["City"] = (c["City"].str.strip().str.title())
c.head()

/tmp/ipykernel_3627/2377516247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["Customer_Name"] = (c["Customer_Name"].str.strip().str.title())
/tmp/ipykernel_3627/2377516247.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["City"] = (c["City"].str.strip().str.title())

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bengaluru,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [49]:
c["City"]=c["City"].replace("Bengaluru","Bangalore")
c.head()

/tmp/ipykernel_3627/1625523585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["City"]=c["City"].replace("Bengaluru","Bangalore")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,01/09/2026,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026/09/02,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,03-09-2026,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [50]:
c["Order_Date"].dtype

dtype('O')

In [51]:
c["Order_Date"] = pd.to_datetime(c["Order_Date"],errors = "coerce")
c.head()

/tmp/ipykernel_3627/3237822196.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["Order_Date"] = pd.to_datetime(c["Order_Date"],errors = "coerce")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,NaT,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,NaT,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0

In [53]:
c["Order_Date"].isnull().sum()

np.int64(25)

In [54]:
c[c["Order_Date"].isnull()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,NaT,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,NaT,Card,Suresh,3.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,NaT,Cash,Ravi,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,NaT,Upi,Meena,5.0
10,1011,Rohit Das,Pune,Monitor,Electronics,1,11800.0,NaT,Cash,Meena,5.0
13,1014,Pooja Menon,Kochi,Desk,Furniture,1,7800.0,NaT,Card,Suresh,5.0
15,1016,Sanjay Rao,Chennai,Webcam,Accessories,2,3100.0,NaT,Cash,Ravi,3.0
17,1018,Ajay Kumar,Delhi,Laptop Stand,Accessories,1,2100.0,NaT,Upi,Meena,5.0
19,1020,Varun Shah,Mumbai,Monitor,Electronics,2,12000.0,NaT,Card,Suresh,3.0
23,1024,Suresh Kumar,Hyderabad,Mouse,Electronics,4,820.0,NaT,Cash,Meena,5.0
25,1026,Gokul Raj,Delhi,Headphones,Electronics,2,2750.0,NaT,Upi,Suresh,3.0
27,1028,Deepak Singh,Kolkata,Laptop,Electronics,1,54000.0,NaT,Card,Ravi,4.0
29,1030,Naveen P,Chennai,Desk,Furniture,1,8000.0,NaT,Cash,Meena,4.0
31,1032,Hari Krish,Hyderabad,Keyboard,Electronics,1,1850.0,NaT,Card,Suresh,4.0
32,1033,Swathi Rao,Mumbai,Mouse,Electronics,2,900.0,NaT,Cash,Meena,3.0
33,1034,Prakash N,Mumbai,Webcam,Accessories,1,3150.0,NaT,Upi,Ravi,4.0
35,1036,Mohan Raj,Delhi,Laptop Stand,Accessories,3,2050.0,NaT,Cash,Meena,4.0
37,1038,Abhishek T,Kolkata,Laptop,Electronics,1,57000.0,NaT,Card,Suresh,4.0
39,1040,Naveen P,Chennai,Mouse,Electronics,2,780.0,NaT,Upi,Ravi,4.0
41,1042,Siva Kumar,Hyderabad,Office Chair,Furniture,1,6100.0,NaT,Cash,Meena,4.0
43,1044,Rahul Verma,Chennai,Laptop,Electronics,1,55500.0,NaT,Card,Suresh,4.0
46,1047,Rohit Das,Pune,Headphones,Electronics,2,2850.0,NaT,Card,Suresh,3.0
49,1050,Vikram J,Bangalore,Office Chair,Furniture,1,6600.0,NaT,Card,Suresh,5.0
50,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,NaT,Upi,Ravi,4.0

In [55]:
c["Order_Date"] = c["Order_Date"].fillna("2026-01-01")
c.head(10)

/tmp/ipykernel_3627/2707205118.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["Order_Date"] = c["Order_Date"].fillna("2026-01-01")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,2026-09-01,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,2026-01-01,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,2026-01-01,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,2026-01-01,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,2026-09-03,Card,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,2026-01-01,Cash,Ravi,4.0
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.0,2026-09-05,Cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,2026-01-01,Upi,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,2026-09-06,Upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,2026-09-07,Card,Suresh,4.0

In [56]:
c["Order_Date"] = c["Order_Date"].dt.month

/tmp/ipykernel_3627/697147261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["Order_Date"] = c["Order_Date"].dt.month

In [57]:
c.head(10)

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,9,Cash,Ravi,4.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,1,Upi,Meena,5.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,1,Upi,Ravi,4.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,1,Card,Suresh,3.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,9,Card,Meena,5.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,1,Cash,Ravi,4.0
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.0,9,Cash,Suresh,4.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,1,Upi,Meena,5.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,9,Upi,Ravi,3.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,9,Card,Suresh,4.0

In [59]:
c["Quantity"] = pd.to_numeric(c["Quantity"],errors="coerce")

/tmp/ipykernel_3627/1012448561.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["Quantity"] = pd.to_numeric(c["Quantity"],errors="coerce")

In [60]:
c[c["Quantity"].isnull()]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Price, Order_Date, Payment_Mode, Salesperson, Customer_Rating]
Index: []

In [61]:
c.dtypes

Order_ID             int64
Customer_Name       object
City                object
Product             object
Category            object
Quantity             int64
Price              float64
Order_Date           int32
Payment_Mode        object
Salesperson         object
Customer_Rating    float64
dtype: object

In [62]:
c["Total_Price"] = (c["Quantity"]*c["Price"])

/tmp/ipykernel_3627/3657785946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c["Total_Price"] = (c["Quantity"]*c["Price"])

In [63]:
c.head(10)

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Order_Date,Payment_Mode,Salesperson,Customer_Rating,Total_Price
0,1001,Arun Kumar,Chennai,Laptop,Electronics,1,55000.0,9,Cash,Ravi,4.0,55000.0
1,1002,Priya Sharma,Chennai,Mouse,Electronics,2,850.0,1,Upi,Meena,5.0,1700.0
2,1003,Rahul Verma,Chennai,Keyboard,Electronics,1,1800.0,1,Upi,Ravi,4.0,1800.0
3,1004,Divya Raj,Bangalore,Monitor,Electronics,1,12500.0,1,Card,Suresh,3.0,12500.0
4,1005,Karthik S,Bangalore,Office Chair,Furniture,2,6500.0,9,Card,Meena,5.0,13000.0
5,1006,Unknown,Hyderabad,Desk,Furniture,1,8500.0,1,Cash,Ravi,4.0,8500.0
6,1007,Vijay Kumar,Hyderabad,Laptop Stand,Accessories,2,2200.0,9,Cash,Suresh,4.0,4400.0
7,1008,Anjali Rao,Mumbai,Webcam,Accessories,1,3200.0,1,Upi,Meena,5.0,3200.0
8,1009,Manoj Patel,Mumbai,Headphones,Electronics,1,780.0,9,Upi,Ravi,3.0,780.0
9,1010,Asha Nair,Pune,Keyboard,Electronics,2,1750.0,9,Card,Suresh,4.0,3500.0

In [64]:
c[["Product","Quantity","Price","Total_Price"]]

         Product  Quantity    Price  Total_Price
0         Laptop         1  55000.0      55000.0
1          Mouse         2    850.0       1700.0
2       Keyboard         1   1800.0       1800.0
3        Monitor         1  12500.0      12500.0
4   Office Chair         2   6500.0      13000.0
5           Desk         1   8500.0       8500.0
6   Laptop Stand         2   2200.0       4400.0
7         Webcam         1   3200.0       3200.0
8     Headphones         1    780.0        780.0
9       Keyboard         2   1750.0       3500.0
10       Monitor         1  11800.0      11800.0
12        Laptop         1  55000.0      55000.0
13          Desk         1   7800.0       7800.0
14         Mouse         3    800.0       2400.0
15        Webcam         2   3100.0       6200.0
17  Laptop Stand         1   2100.0       2100.0
18        Laptop         1  56000.0      56000.0
19       Monitor         2  12000.0      24000.0
20  Office Chair         1   6400.0       6400.0
22      Keyboard         1   1900.0       1900.0
23         Mouse         4    820.0       3280.0
24        Webcam         1   3300.0       3300.0
25    Headphones         2   2750.0       5500.0
26  Laptop Stand         2   2300.0       4600.0
27        Laptop         1  54000.0      54000.0
29          Desk         1   8000.0       8000.0
30  Office Chair         2   6300.0      12600.0
31      Keyboard         1   1850.0       1850.0
32         Mouse         2    900.0       1800.0
33        Webcam         1   3150.0       3150.0
35  Laptop Stand         3   2050.0       6150.0
36       Monitor         1  12100.0      12100.0
37        Laptop         1  57000.0      57000.0
38          Desk         1   7900.0       7900.0
39         Mouse         2    780.0       1560.0
40      Keyboard         1   1800.0       1800.0
41  Office Chair         1   6100.0       6100.0
42        Webcam         2   3250.0       6500.0
43        Laptop         1  55500.0      55500.0
44       Monitor         1  12300.0      12300.0
46    Headphones         2   2850.0       5700.0
48         Mouse         2    780.0       1560.0
49  Office Chair         1   6600.0       6600.0
50      Keyboard         1   1800.0       1800.0
51         Mouse         3    800.0       2400.0
52      Keyboard         2   1750.0       3500.0

In [65]:
c.isnull().sum()

Order_ID           0
Customer_Name      0
City               0
Product            0
Category           0
Quantity           0
Price              0
Order_Date         0
Payment_Mode       0
Salesperson        0
Customer_Rating    0
Total_Price        0
dtype: int64

In [66]:
c.duplicated().sum()

np.int64(2)

In [69]:
c=c.drop_duplicates()

In [70]:
c.duplicated().sum()

np.int64(0)

In [71]:
c["City"].value_counts()

City
Chennai      11
Hyderabad     6
Bangalore     5
Mumbai        5
Pune          5
Kochi         4
Delhi         4
Kolkata       4
Name: count, dtype: int64

In [72]:
print(c["City"].value_counts())

City
Chennai      11
Hyderabad     6
Bangalore     5
Mumbai        5
Pune          5
Kochi         4
Delhi         4
Kolkata       4
Name: count, dtype: int64

In [75]:
c.groupby("Product")["Total_Price"].sum()

Product
Desk             32200.0
Headphones       11980.0
Keyboard         14350.0
Laptop          332500.0
Laptop Stand     17250.0
Monitor          72700.0
Mouse            12300.0
Office Chair     44700.0
Webcam           22350.0
Name: Total_Price, dtype: float64

In [76]:
new_table= pd.DataFrame(c.groupby("Product")["Total_Price"].sum())

In [80]:
new_table.sort_values("Total_Price",ascending=False)

              Total_Price
Product
Laptop           332500.0
Monitor           72700.0
Office Chair      44700.0
Desk              32200.0
Webcam            22350.0
Laptop Stand      17250.0
Keyboard          14350.0
Mouse             12300.0
Headphones        11980.0

In [81]:
sales_by_category = pd.DataFrame(c.groupby("Category")["Total_Price"].sum())

In [83]:
c.groupby("City")["Total_Price"].sum().sort_values(ascending=False)

City
Chennai      216060.0
Kolkata      127700.0
Hyderabad     80130.0
Bangalore     35800.0
Mumbai        32930.0
Pune          27800.0
Delhi         20250.0
Kochi         19660.0
Name: Total_Price, dtype: float64

In [86]:
c.groupby("City").agg(
    Orders=("Order_ID", "count"),
    Total_Sales=("Total_Price", "sum"),
    Average_Rating=("Customer_Rating", "mean")
)

           Orders  Total_Sales  Average_Rating
City
Bangalore       5      35800.0        4.000000
Chennai        11     216060.0        4.272727
Delhi           4      20250.0        4.250000
Hyderabad       6      80130.0        4.166667
Kochi           4      19660.0        4.500000
Kolkata         4     127700.0        4.500000
Mumbai          5      32930.0        3.600000
Pune            5      27800.0        4.000000

In [87]:
c.to_csv("Customer_Dataset_Cleaned.csv",index=False)